Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String

Resources:
  # Allow tasks using the environment SG to communicate with each other
  TaskToTaskIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::ImportValue: !Sub ${App}-${Env}-EnvironmentSecurityGroup
      IpProtocol: tcp
      FromPort: 3001
      ToPort: 3001
      SourceSecurityGroupId:
        Fn::ImportValue: !Sub ${App}-${Env}-EnvironmentSecurityGroup
      Description: Allow shared API to reach per-user tasks on port 3001

  EcsTaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: EcsProvisionAccess
            Effect: Allow
            Action:
              - ecs:DescribeTasks
              - ecs:DescribeServices
              - ecs:RunTask
              - ecs:StopTask
            Resource: "*"
            Condition:
              ArnEquals:
                ecs:cluster: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${App}-${Env}-Cluster*
          - Sid: PassRoleForRunTask
            Effect: Allow
            Action:
              - iam:PassRole
            Resource: "*"
            Condition:
              StringLike:
                iam:PassedToService: ecs-tasks.amazonaws.com

Outputs:
  EcsTaskPolicyArn:
    Value: !Ref EcsTaskPolicy
